# banlist-url: The URL to check for the banlist
# fields: Important field names to search for
#   ign: The field name used for player in-game names
#   uuid: The field name used for player UUIDs
# ban-message: The message to be sent to banned players. May contain field 
#              values where the field name is specified inside {curly braces}
# max-bandwidth: The maximum bandwidth to allocate to loading the banlist in 
#                kB/sec (faster values load the banlist quicker, lower values 
#                reduce the impact of denial of service attacks from the banlist 
#                server)
# timeout: The time in seconds before the connection to the banlist server times 
#          out (longer time deals with larger banlists better, shorter time
#          reduces the duration of denial of service attacks from the banlist
#          server
# retries: How many times to attempt to reconnect to the server if it fails to
#          connect before falling back on the local UBL backup
# auto-check-interval: How often (in minutes) to check the UBL and update it (0 
#                      for startup only)
# exempt: a list of players exempt from the UBL on this server
---
banlist-url: 'https://docs.google.com/spreadsheet/ccc?key=0AjACyg1Jc3_GdEhqWU5PTEVHZDVLYWphd2JfaEZXd2c&output=csv'
fields:
  ign: IGN
  uuid: UUID
ban-message: 'UBL - {Reason} - {Courtroom Post}'
max-bandwidth: 64
timeout: 5
retries: 3
auto-check-interval: 0
exempt: []
